### PR TITLE
N dimensional es

### PR DESCRIPTION
**Pull request by nickwilliamsnewby**
I added a tree to the es hyperneat transcriber file can subdivide its self accordingly given coords in any number n dimensions

### CODE REVIEW

**Comment by nickwilliamsnewby** [comment]
im working on implementing division initialization and the pruning to work with this now in the pureples (python) library, if i get it working there i will let you know and start doing the same in this lib

**Comment by nickwilliamsnewby** [comment]
https://github.com/nickwilliamsnewby/pureples/tree/n-dimensional-tree in the es-hyperneat.py file is all the code you should need to reference to implement this in your lib, I will try to get it done on my end but i have a sneaking suspicion your more far more adept in java (definitely more familiar with the lib lol)  than I so I figured I would reach out

**Comment by OliverColeman** [comment]
Hi Nick, I'm no longer maintaining this library. Would you like me to add you as a contributor so you can add this and other stuff as you see fit?

**Comment by nickwilliamsnewby** [comment]
Yeah that would be great Oliver thanks!

**Comment by OliverColeman** [comment]
Done :)

**Comment by nickwilliamsnewby** [comment]
awesome thank you!

**Pull request merged**
